## Video 1

In [1]:
import numpy as np

In [2]:
L = [1, 2, 3]

In [3]:
A = np.array([1, 2, 3])

In [4]:
for e in L:
    print(e)

1
2
3


In [6]:
for e in A:
    print(e)

1
2
3


In [7]:
L.append(4)

In [9]:
A.append(4) # no append function in Array

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [10]:
L = L + [5]

In [11]:
A = A + [4, 5]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [12]:
L

[1, 2, 3, 4, 5]

In [14]:
A + A # Vector Addition

array([2, 4, 6])

In [15]:
2 * A

array([2, 4, 6])

In [16]:
L + L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [17]:
2 * L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [18]:
np.sqrt(A)

array([ 1.        ,  1.41421356,  1.73205081])

In [19]:
np.log(A)

array([ 0.        ,  0.69314718,  1.09861229])

In [20]:
np.exp(A)

array([  2.71828183,   7.3890561 ,  20.08553692])

## Video 2

In [22]:
a = np.array([1, 2])

In [23]:
b = np.array([2, 1])

In [24]:
dot = 0
for e, f in zip(a, b):
    dot += e*f
dot

4

In [26]:
dot = np.sum(a*b)
dot

4

In [27]:
(a*b).sum()

4

In [28]:
np.dot(a, b)

4

In [29]:
a.dot(b)

4

In [31]:
amag = np.sqrt((a*a).sum())
amag

2.2360679774997898

In [32]:
amag = np.linalg.norm(a)
amag

2.2360679774997898

In [34]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosangle

0.79999999999999982

In [36]:
angle_radians = np.arccos(cosangle)
print(angle_radians)

0.643501108793


## Video 3

In [37]:
import numpy as np
from datetime import datetime

In [38]:
a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

In [39]:
def slow_dot_product(a, b):
    result = 0
    for e, f in zip(a, b):
        result += a*b
    return result

In [40]:
t0 = datetime.now()
for t in range(T):
    slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
    a.dot(b)
dt2 = datetime.now() - t0    

In [43]:
print(dt1.total_seconds()/dt2.total_seconds())

206.6761440607963


## Video 4

In [44]:
M = np.array([[1, 2], [3, 4]])
L = [[1, 2], [3, 4]]

In [45]:
L[0]

[1, 2]

In [46]:
L[0][0]

1

In [47]:
M.T

array([[1, 3],
       [2, 4]])

## Video 5

In [48]:
np.array([1, 2, 3])

array([1, 2, 3])

In [50]:
Z = np.zeros(10)
Z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])